/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoodbyeRouteImport } from './routes/goodbye'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as StatisticsIndexRouteImport } from './routes/statistics/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as TournamentsCreateRouteImport } from './routes/tournaments/create'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments/$tournamentId'
import { Route as TeamsCreateRouteImport } from './routes/teams/create'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as StatisticsPlayerIdRouteImport } from './routes/statistics/$playerId'
import { Route as PlayersCreateRouteImport } from './routes/players/create'
import { Route as MatchesCreateMatchRouteImport } from './routes/matches/create-match'
import { Route as MatchesCreateRouteImport } from './routes/matches/create'
import { Route as MatchesCompletedRouteImport } from './routes/matches/completed'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as TournamentsTournamentIdEditRouteImport } from './routes/tournaments/$tournamentId/edit'
import { Route as TeamsTeamIdStatsRouteImport } from './routes/teams/$teamId/stats'
import { Route as TeamsTeamIdAssignPlayersRouteImport } from './routes/teams/$teamId/assign-players'
import { Route as MatchesMatchIdScorecardRouteImport } from './routes/matches/$matchId/scorecard'
import { Route as MatchesMatchIdScoreRouteImport } from './routes/matches/$matchId/score'

const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsIndexRoute = StatisticsIndexRouteImport.update({
  id: '/statistics/',
  path: '/statistics/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsCreateRoute = TournamentsCreateRouteImport.update({
  id: '/tournaments/create',
  path: '/tournaments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/tournaments/$tournamentId',
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsCreateRoute = TeamsCreateRouteImport.update({
  id: '/teams/create',
  path: '/teams/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsPlayerIdRoute = StatisticsPlayerIdRouteImport.update({
  id: '/statistics/$playerId',
  path: '/statistics/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersCreateRoute = PlayersCreateRouteImport.update({
  id: '/players/create',
  path: '/players/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesCreateMatchRoute = MatchesCreateMatchRouteImport.update({
  id: '/matches/create-match',
  path: '/matches/create-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesCreateRoute = MatchesCreateRouteImport.update({
  id: '/matches/create',
  path: '/matches/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesCompletedRoute = MatchesCompletedRouteImport.update({
  id: '/matches/completed',
  path: '/matches/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)
const TournamentsTournamentIdEditRoute =
  TournamentsTournamentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)
const TeamsTeamIdStatsRoute = TeamsTeamIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdAssignPlayersRoute =
  TeamsTeamIdAssignPlayersRouteImport.update({
    id: '/assign-players',
    path: '/assign-players',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)
const MatchesMatchIdScorecardRoute = MatchesMatchIdScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)
const MatchesMatchIdScoreRoute = MatchesMatchIdScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/goodbye': typeof GoodbyeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organize': typeof OrganizeRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/matches/completed': typeof MatchesCompletedRoute
  '/matches/create': typeof MatchesCreateRoute
  '/matches/create-match': typeof MatchesCreateMatchRoute
  '/players/create': typeof PlayersCreateRoute
  '/statistics/$playerId': typeof StatisticsPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/scorecard': typeof MatchesMatchIdScorecardRoute
  '/teams/$teamId/assign-players': typeof TeamsTeamIdAssignPlayersRoute
  '/teams/$teamId/stats': typeof TeamsTeamIdStatsRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/goodbye': typeof GoodbyeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organize': typeof OrganizeRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/matches/completed': typeof MatchesCompletedRoute
  '/matches/create': typeof MatchesCreateRoute
  '/matches/create-match': typeof MatchesCreateMatchRoute
  '/players/create': typeof PlayersCreateRoute
  '/statistics/$playerId': typeof StatisticsPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/create': typeof TournamentsCreateRoute
  '/matches': typeof MatchesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/statistics': typeof StatisticsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/scorecard': typeof MatchesMatchIdScorecardRoute
  '/teams/$teamId/assign-players': typeof TeamsTeamIdAssignPlayersRoute
  '/teams/$teamId/stats': typeof TeamsTeamIdStatsRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/goodbye': typeof GoodbyeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organize': typeof OrganizeRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/matches/completed': typeof MatchesCompletedRoute
  '/matches/create': typeof MatchesCreateRoute
  '/matches/create-match': typeof MatchesCreateMatchRoute
  '/players/create': typeof PlayersCreateRoute
  '/statistics/$playerId': typeof StatisticsPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteWithChildren
  '/tournaments/create': typeof TournamentsCreateRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/scorecard': typeof MatchesMatchIdScorecardRoute
  '/teams/$teamId/assign-players': typeof TeamsTeamIdAssignPlayersRoute
  '/teams/$teamId/stats': typeof TeamsTeamIdStatsRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/goodbye'
    | '/login'
    | '/onboarding'
    | '/organize'
    | '/matches/$matchId'
    | '/matches/completed'
    | '/matches/create'
    | '/matches/create-match'
    | '/players/create'
    | '/statistics/$playerId'
    | '/teams/$teamId'
    | '/teams/create'
    | '/tournaments/$tournamentId'
    | '/tournaments/create'
    | '/matches/'
    | '/players/'
    | '/statistics/'
    | '/teams/'
    | '/tournaments/'
    | '/matches/$matchId/score'
    | '/matches/$matchId/scorecard'
    | '/teams/$teamId/assign-players'
    | '/teams/$teamId/stats'
    | '/tournaments/$tournamentId/edit'
    | '/tournaments/$tournamentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/goodbye'
    | '/login'
    | '/onboarding'
    | '/organize'
    | '/matches/$matchId'
    | '/matches/completed'
    | '/matches/create'
    | '/matches/create-match'
    | '/players/create'
    | '/statistics/$playerId'
    | '/teams/$teamId'
    | '/teams/create'
    | '/tournaments/create'
    | '/matches'
    | '/players'
    | '/statistics'
    | '/teams'
    | '/tournaments'
    | '/matches/$matchId/score'
    | '/matches/$matchId/scorecard'
    | '/teams/$teamId/assign-players'
    | '/teams/$teamId/stats'
    | '/tournaments/$tournamentId/edit'
    | '/tournaments/$tournamentId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/goodbye'
    | '/login'
    | '/onboarding'
    | '/organize'
    | '/matches/$matchId'
    | '/matches/completed'
    | '/matches/create'
    | '/matches/create-match'
    | '/players/create'
    | '/statistics/$playerId'
    | '/teams/$teamId'
    | '/teams/create'
    | '/tournaments/$tournamentId'
    | '/tournaments/create'
    | '/matches/'
    | '/players/'
    | '/statistics/'
    | '/teams/'
    | '/tournaments/'
    | '/matches/$matchId/score'
    | '/matches/$matchId/scorecard'
    | '/teams/$teamId/assign-players'
    | '/teams/$teamId/stats'
    | '/tournaments/$tournamentId/edit'
    | '/tournaments/$tournamentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  GoodbyeRoute: typeof GoodbyeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizeRoute: typeof OrganizeRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRouteWithChildren
  MatchesCompletedRoute: typeof MatchesCompletedRoute
  MatchesCreateRoute: typeof MatchesCreateRoute
  MatchesCreateMatchRoute: typeof MatchesCreateMatchRoute
  PlayersCreateRoute: typeof PlayersCreateRoute
  StatisticsPlayerIdRoute: typeof StatisticsPlayerIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRouteWithChildren
  TeamsCreateRoute: typeof TeamsCreateRoute
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRouteWithChildren
  TournamentsCreateRoute: typeof TournamentsCreateRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  StatisticsIndexRoute: typeof StatisticsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/': {
      id: '/statistics/'
      path: '/statistics'
      fullPath: '/statistics/'
      preLoaderRoute: typeof StatisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/create': {
      id: '/tournaments/create'
      path: '/tournaments/create'
      fullPath: '/tournaments/create'
      preLoaderRoute: typeof TournamentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/create': {
      id: '/teams/create'
      path: '/teams/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof TeamsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/$playerId': {
      id: '/statistics/$playerId'
      path: '/statistics/$playerId'
      fullPath: '/statistics/$playerId'
      preLoaderRoute: typeof StatisticsPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/create': {
      id: '/players/create'
      path: '/players/create'
      fullPath: '/players/create'
      preLoaderRoute: typeof PlayersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/create-match': {
      id: '/matches/create-match'
      path: '/matches/create-match'
      fullPath: '/matches/create-match'
      preLoaderRoute: typeof MatchesCreateMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/create': {
      id: '/matches/create'
      path: '/matches/create'
      fullPath: '/matches/create'
      preLoaderRoute: typeof MatchesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/completed': {
      id: '/matches/completed'
      path: '/matches/completed'
      fullPath: '/matches/completed'
      preLoaderRoute: typeof MatchesCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/'
      fullPath: '/tournaments/$tournamentId/'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof TournamentsTournamentIdRoute
    }
    '/tournaments/$tournamentId/edit': {
      id: '/tournaments/$tournamentId/edit'
      path: '/edit'
      fullPath: '/tournaments/$tournamentId/edit'
      preLoaderRoute: typeof TournamentsTournamentIdEditRouteImport
      parentRoute: typeof TournamentsTournamentIdRoute
    }
    '/teams/$teamId/stats': {
      id: '/teams/$teamId/stats'
      path: '/stats'
      fullPath: '/teams/$teamId/stats'
      preLoaderRoute: typeof TeamsTeamIdStatsRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/assign-players': {
      id: '/teams/$teamId/assign-players'
      path: '/assign-players'
      fullPath: '/teams/$teamId/assign-players'
      preLoaderRoute: typeof TeamsTeamIdAssignPlayersRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/matches/$matchId/scorecard': {
      id: '/matches/$matchId/scorecard'
      path: '/scorecard'
      fullPath: '/matches/$matchId/scorecard'
      preLoaderRoute: typeof MatchesMatchIdScorecardRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/matches/$matchId/score': {
      id: '/matches/$matchId/score'
      path: '/score'
      fullPath: '/matches/$matchId/score'
      preLoaderRoute: typeof MatchesMatchIdScoreRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
  }
}

interface MatchesMatchIdRouteChildren {
  MatchesMatchIdScoreRoute: typeof MatchesMatchIdScoreRoute
  MatchesMatchIdScorecardRoute: typeof MatchesMatchIdScorecardRoute
}

const MatchesMatchIdRouteChildren: MatchesMatchIdRouteChildren = {
  MatchesMatchIdScoreRoute: MatchesMatchIdScoreRoute,
  MatchesMatchIdScorecardRoute: MatchesMatchIdScorecardRoute,
}

const MatchesMatchIdRouteWithChildren = MatchesMatchIdRoute._addFileChildren(
  MatchesMatchIdRouteChildren,
)

interface TeamsTeamIdRouteChildren {
  TeamsTeamIdAssignPlayersRoute: typeof TeamsTeamIdAssignPlayersRoute
  TeamsTeamIdStatsRoute: typeof TeamsTeamIdStatsRoute
}

const TeamsTeamIdRouteChildren: TeamsTeamIdRouteChildren = {
  TeamsTeamIdAssignPlayersRoute: TeamsTeamIdAssignPlayersRoute,
  TeamsTeamIdStatsRoute: TeamsTeamIdStatsRoute,
}

const TeamsTeamIdRouteWithChildren = TeamsTeamIdRoute._addFileChildren(
  TeamsTeamIdRouteChildren,
)

interface TournamentsTournamentIdRouteChildren {
  TournamentsTournamentIdEditRoute: typeof TournamentsTournamentIdEditRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
}

const TournamentsTournamentIdRouteChildren: TournamentsTournamentIdRouteChildren =
  {
    TournamentsTournamentIdEditRoute: TournamentsTournamentIdEditRoute,
    TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
  }

const TournamentsTournamentIdRouteWithChildren =
  TournamentsTournamentIdRoute._addFileChildren(
    TournamentsTournamentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  GoodbyeRoute: GoodbyeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizeRoute: OrganizeRoute,
  MatchesMatchIdRoute: MatchesMatchIdRouteWithChildren,
  MatchesCompletedRoute: MatchesCompletedRoute,
  MatchesCreateRoute: MatchesCreateRoute,
  MatchesCreateMatchRoute: MatchesCreateMatchRoute,
  PlayersCreateRoute: PlayersCreateRoute,
  StatisticsPlayerIdRoute: StatisticsPlayerIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRouteWithChildren,
  TeamsCreateRoute: TeamsCreateRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRouteWithChildren,
  TournamentsCreateRoute: TournamentsCreateRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  StatisticsIndexRoute: StatisticsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
